version: 2.1

jobs:
  dsbaseclient_base:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layout_caching: true
      - run:
          name: Display settings
          command: |
            echo "Building"
            echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
            echo "  Branch:    " $CIRCLE_BRANCH
            echo "  Build Num: " $CIRCLE_BUILD_NUM
            echo "  Tag:       " $CIRCLE_TAG
      - run:
          name: Build and push docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t datashield/dsbaseclient-base:$TAG --file dsBaseClient_Dockerfile .
            docker login docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push datashield/dsbaseclient-base:$TAG
workflows:
  build:
    jobs:
      - dsbaseclient_base
